In [ ]:
# Pandas Data Science Library
import numpy as np
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
# numpy --> array()
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]

In [ ]:
# Pandas Series
# Series is 1D Labelled Array

s = pd.Series([10,20,30,40,50])
print(type(s))
print(s)
print(s.shape)

# In numpy --> Only Numbers
# In series --> Numbers + Labels (index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64
(5,)

In [ ]:
info = pd.Series(['John', 26, 6700, 'Klang'], index = ['Name', 'Age', 'Salary', 'City'])
print(info)
print(info['Name']) # Indexing
print(info.get('City')) # Getting data values using get()

Name       John
Age          26
Salary     6700
City      Klang
dtype: object
John
Klang

In [ ]:
info = pd.Series(['John', 26, 6700, 'Klang'], index = ['Name', 'Age', 'Salary', 'City'])
print(type(info))
print(info['Name'])  # indexing
print(info.get('City')) # Getting data values using get()
print(info[0])  # iloc --> index location

# Series is like a dictionary + array combo

<class 'pandas.core.series.Series'>
John
Klang
John

/tmp/ipykernel_254/1219685029.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(info[0])  # iloc --> index location

In [ ]:
# Indexing Slicing And Using For Loop
s = pd.Series([100,200,300,400,500, 600], index=['v1', 'v2', 'v3', 'v4', 'v5', 'v6'])
print(s)

# 100 200 300 400 500 600
# -6  -5  -4  -3  -2  -1
#v1  v2   v3  v4  v5  v6

# Indexing in Series can be done by using [] or iloc[] or Loc[]
print(' \nIndexing In Series')
print(s.iloc[0])
# for index numbers
print(s.loc['v5'])
# Loc used for Labels
print(s['v2'])
# [] used for Labels
print (s.iloc[-1])

print('\nSlicing In Series')
print(s[1:4]) # 4 will be excluded --> stopIndex
print(s['v1':'v5']) # if performing slicing using labels, the end label will be included

# 100 400 600
print(s[['v1','v4','v6']]) # for specific information s[['','','']]
print(s[['v1','v4','v6']].values)

# conditional selection
print('\nConditional In Series')
print(s[s%3==0])

v1    100
v2    200
v3    300
v4    400
v5    500
v6    600
dtype: int64

Indexing In Series
100
500
200
600

Slicing In Series
v2    200
v3    300
v4    400
dtype: int64
v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64
v1    100
v4    400
v6    600
dtype: int64
[100 400 600]

Conditional In Series
v3    300
v6    600
dtype: int64

In [ ]:
# using for loop
for i in s:
  print(i)

100
200
300
400
500
600

In [ ]:
for k,v in s.items():
  print(k,v)

v1 100
v2 200
v3 300
v4 400
v5 500
v6 600

In [ ]:
for i in enumerate(s):
  print(i)

(0, 100)
(1, 200)
(2, 300)
(3, 400)
(4, 500)
(5, 600)

In [ ]:
# Pandas DataFrame
# it is used to display the information in a tabular fashion
# Pandas DataFrame is 2D Array

data = {
    'name':['John','Alex','Smith'],
    'dept':['IT','HR','MR'],
    'sal':[6700,5600,6000],
    'city':['KL','JB','ML']
}
print(data)

{'name': ['John', 'Alex', 'Smith'], 'dept': ['IT', 'HR', 'MR'], 'sal': [6700, 5600, 6000], 'city': ['KL', 'JB', 'ML']}

In [ ]:
df = pd.DataFrame(data)
df

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

In [ ]:
print(df.shape)

(3, 4)

In [ ]:
data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}
df = pd.DataFrame(data, index=['Day 1','Day 2','Day 3'])
df

       Calories  Duration
Day 1       420        56
Day 2       380        30
Day 3       560        75

In [ ]:
df['Calories']

Day 1    420
Day 2    380
Day 3    560
Name: Calories, dtype: int64

In [ ]:
df['Calories'].values

array([420, 380, 560])

In [ ]:
df.loc['Day 1']

Calories    420
Duration     56
Name: Day 1, dtype: int64

In [ ]:
df.loc[['Day 1','Day 3']]

       Calories  Duration
Day 1       420        56
Day 3       560        75